export const SET_START_MODAL_VISIBLE = "SET_START_MODAL_VISIBLE";
export const SET_STOP_MODAL_VISIBLE = "SET_STOP_MODAL_VISIBLE";
export const SET_DELETE_MODAL_VISIBLE = "SET_DELETE_MODAL_VISIBLE";
export const SET_QUESTION_LIST = "SET_QUESTION_LIST";
export const SET_CURRENT_QUESTION_ITEM_ID = "SET_CURRENT_QUESTION_ITEM_ID";
export const SET_ANSWER_LIST = "SET_ANSWER_LIST";
export const SET_INTERACT_LIST = "SET_INTERACT_LIST";
