export const SET_START_MODAL_VISIBLE = "SET_START_MODAL_VISIBLE";
export const SET_STOP_MODAL_VISIBLE = "SET_STOP_MODAL_VISIBLE";
export const SET_INTERACT_IS_START = "SET_INTERACT_IS_START";
export const SET_INTERACT_IS_FINISHED = "SET_INTERACT_IS_FINISHED";
export const SET_QUESTION_LIST = "SET_QUESTION_LIST";
export const SET_CURRENT_INDEX = "SET_CURRENT_INDEX";
